exports.PUBLIC_SCOPED_SDK = [
  "cmdb",
  "micro-app",
  "micro-app-standalone",
  "monitor",
  "msgsender",
  "next-builder",
  "object-store",
  "permission",
  "user-service",
  "air-admin-service",
  "api-gateway",
  "sys-setting",
  "form-builder-service",
];
